# Generated by Gemini
# Standard Shift Test (Pass = "0", Fail = "1")
# Tests 8XY6 (Right Shift) and 8XYE (Left Shift)

from pathlib import Path

def create_rom():
    rom = bytes([
        # -- SETUP (0x200) --
        0x00, 0xE0, # Clear Screen

        # -- TEST 1: RIGHT SHIFT (0x202) --
        # V0 = 1. After shift, VF should be 1.
        0x60, 0x01, # V0 = 1
        0x80, 0x06, # V0 >>= 1
        
        # Check: If VF == 1, Skip the "Jump to Fail"
        0x3F, 0x01, 
        
        # If logic failed (VF != 1), we hit this:
        0x12, 0x1E, # Jump to FAIL (0x21E)

        # -- TEST 2: LEFT SHIFT (0x208) --
        # V0 = 0x80 (10000000). After shift, VF should be 1.
        0x60, 0x80, # V0 = 128
        0x80, 0x0E, # V0 <<= 1
        
        # Check: If VF == 1, Skip the "Jump to Fail"
        0x3F, 0x01, 
        
        # If logic failed (VF != 1), we hit this:
        0x12, 0x1E, # Jump to FAIL (0x21E)

        # -- JUMP TO SUCCESS (0x210) --
        # If we survived both checks, go to success.
        0x12, 0x16, 

        # -- PAD (0x212, 0x214) --
        0x00, 0x00, 0x00, 0x00,

        # -- SUCCESS ROUTINE (0x216) --
        0xA0, 0x50, # I = Address of Sprite "0" (Pass)
        0x12, 0x22, # Jump to Draw (0x222)

        # -- PAD (0x21A, 0x21C) --
        0x00, 0x00, 0x00, 0x00,

        # -- FAIL ROUTINE (0x21E) --
        0xA0, 0x55, # I = Address of Sprite "1" (Fail)
        
        # -- PAD (0x220) --
        0x00, 0x00,

        # -- DRAW SHARED (0x222) --
        0x62, 0x00, # V2 = 0
        0xD2, 0x25, # Draw sprite at (0,0) with height 5
        
        # -- INFINITE LOOP (0x226) --
        0x12, 0x26  # Jump to self
    ])

    out_dir = Path(__file__).resolve().parent / "../binaries"
    out_dir.mkdir(parents=True, exist_ok=True)

    out_path = out_dir / "shift.ch8"
    with open(out_path, "wb") as f:
        f.write(rom)

    print(f"Wrote ROM to {out_path}")

def main():
    create_rom()

if __name__ == "__main__":
    main()